/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class M_UI_UserDetails extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    public M_UI_UserDetails(String exit) {
        initComponents();
        try {
            String url = "jdbc:mysql://localhost/Apple_iStore";
            String user = "root";
            String password = "";

            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected!...");
        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        detailsbtn = new javax.swing.JButton();
        switchbtn = new javax.swing.JButton();
        lgoutbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        newlsbtn1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        deletebtn = new javax.swing.JButton();
        findbtn = new javax.swing.JButton();
        empnamelb = new javax.swing.JLabel();
        empagelb = new javax.swing.JLabel();
        empnametxt = new javax.swing.JTextField();
        empagetxt = new javax.swing.JTextField();
        Updatebtn = new javax.swing.JButton();
        Emppwlb = new javax.swing.JLabel();
        emppwtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sTable2 = new javax.swing.JTable();
        empIDlb1 = new javax.swing.JLabel();
        empIDtxtq = new javax.swing.JTextField();
        refresh1 = new javax.swing.JButton();
        Resetbtn = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(706, 598));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(212, 337));

        detailsbtn.setBackground(new java.awt.Color(153, 0, 0));
        detailsbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        detailsbtn.setForeground(new java.awt.Color(255, 255, 255));
        detailsbtn.setText("User Details.");

        switchbtn.setBackground(new java.awt.Color(153, 0, 0));
        switchbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        switchbtn.setForeground(new java.awt.Color(255, 255, 255));
        switchbtn.setText("Switch to Sales.");
        switchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchbtnActionPerformed(evt);
            }
        });

        lgoutbtn.setBackground(new java.awt.Color(153, 0, 0));
        lgoutbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lgoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        lgoutbtn.setText("Logout");
        lgoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgoutbtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Switch to Manage");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        newlsbtn1.setBackground(new java.awt.Color(153, 0, 0));
        newlsbtn1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        newlsbtn1.setForeground(new java.awt.Color(255, 255, 255));
        newlsbtn1.setText("New User ");
        newlsbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newlsbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(switchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newlsbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(newlsbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(detailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(switchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lgoutbtn)
                .addGap(19, 19, 19))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(447, 520));

        deletebtn.setBackground(new java.awt.Color(153, 0, 0));
        deletebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(255, 255, 255));
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        findbtn.setBackground(new java.awt.Color(153, 0, 0));
        findbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        findbtn.setForeground(new java.awt.Color(255, 255, 255));
        findbtn.setText("FIND");
        findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnActionPerformed(evt);
            }
        });

        empnamelb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empnamelb.setText("Employee Name");

        empagelb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empagelb.setText("Age");

        empagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empagetxtActionPerformed(evt);
            }
        });

        Updatebtn.setBackground(new java.awt.Color(153, 0, 0));
        Updatebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });

        Emppwlb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Emppwlb.setText("Employee Password");

        sTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "User ID", "User Password", "Email"
            }
        ));
        sTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sTable2);

        empIDlb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empIDlb1.setText("Employee ID");

        refresh1.setBackground(new java.awt.Color(153, 0, 0));
        refresh1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        refresh1.setForeground(new java.awt.Color(255, 255, 255));
        refresh1.setText("Refresh");
        refresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh1ActionPerformed(evt);
            }
        });

        Resetbtn.setBackground(new java.awt.Color(153, 0, 0));
        Resetbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Resetbtn.setForeground(new java.awt.Color(255, 255, 255));
        Resetbtn.setText("RESET");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empagelb)
                            .addComponent(empnamelb)
                            .addComponent(Emppwlb)
                            .addComponent(empIDlb1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(findbtn)
                        .addGap(44, 44, 44)
                        .addComponent(Updatebtn)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(deletebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(refresh1)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emppwtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empIDtxtq, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIDlb1)
                    .addComponent(empIDtxtq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empnamelb)
                    .addComponent(empnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empagelb))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emppwlb)
                    .addComponent(emppwtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findbtn)
                    .addComponent(Updatebtn)
                    .addComponent(deletebtn)
                    .addComponent(refresh1))
                .addGap(236, 236, 236)
                .addComponent(Resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(256, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(76, 76, 76)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void switchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        S_UI_SALES sales = new S_UI_SALES("EXIT");
        sales.show();
        
    }//GEN-LAST:event_switchbtnActionPerformed

    private void empagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empagetxtActionPerformed

    private void findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnActionPerformed
       try {
            int id = Integer.parseInt(empIDtxtq.getText());

            String sql = "SELECT * FROM user_details WHERE User_ID=?";

            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);

            rs = pst.executeQuery();
            if (rs.isBeforeFirst()) {
                rs.first();
                empnametxt.setText(rs.getString(1));
                empagetxt.setText(rs.getString(2));
                emppwtxt.setText(rs.getString(5));
                
            } else {
                JOptionPane.showMessageDialog(this, "Student Record Not Found!");
                clear();
            }

        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
    }//GEN-LAST:event_findbtnActionPerformed

    private void refresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM user_details";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) sTable2.getModel();
            model.setRowCount(0);
            if (rs.isBeforeFirst()) {
                while (rs.next()) {
                    model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),
                        rs.getString(4), rs.getString(5), rs.getString(6)});
                }
            } else {
                JOptionPane.showMessageDialog(this, "Students Records Not Found!");
            }

        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
    }//GEN-LAST:event_refresh1ActionPerformed

    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(empIDtxtq.getText());
            String name = empnametxt.getText();
            int age = Integer.parseInt(empagetxt.getText());
            String PW = emppwtxt.getText();

            String sql = "UPDATE user_details SET Name=?, Age=?, Password=? WHERE User_ID=?";
            pst = conn.prepareStatement(sql);

            pst.setString(1, name);
            pst.setInt(2, age);
            pst.setString(3, PW);
            pst.setInt(4, id);

            if (pst.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "User Record Updated");
                clear();
            }else{
                JOptionPane.showMessageDialog(this, "User Record Not Updated");
                clear();
            }
        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        try {
                M_UI_UserDetails frame = new M_UI_UserDetails ("Delete");
                if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to Delete Recode" , "Delete" ,
                        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
                {
            int id = Integer.parseInt(empIDtxtq.getText());

            String sql = "DELETE FROM user_details WHERE User_ID=? ";
            pst = conn.prepareStatement(sql);

            pst.setInt(1, id);

            if (pst.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "User Record Deleted");
            }
           }
        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void newlsbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newlsbtn1ActionPerformed
        // TODO add your handling code here:
        dispose();
        M_UI_addUser nuser  = new  M_UI_addUser("EXIT");
        nuser.show();
    }//GEN-LAST:event_newlsbtn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        S_UI_Manage manage = new  S_UI_Manage("EXIT");
        manage.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbtnActionPerformed
        // TODO add your handling code here:
        empIDtxtq.setText("");
        empnametxt.setText("");
        empagetxt.setText("");
        emppwtxt.setText("");
        

    }//GEN-LAST:event_ResetbtnActionPerformed

    private void lgoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgoutbtnActionPerformed
        // TODO add your handling code here:
         M_UI_UserDetails frame = new M_UI_UserDetails ("EXIT");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit" ,
                "EXIT" ,JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_lgoutbtnActionPerformed

    private void sTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sTable2MouseClicked
        // TODO add your handling code here:
         DefaultTableModel model= (DefaultTableModel)sTable2.getModel();
         int data = sTable2.getSelectedRow();
         empIDtxtq.setText(model.getValueAt(data, 3).toString());
         empnametxt.setText(model.getValueAt(data, 0).toString());
         empagetxt.setText(model.getValueAt(data, 1).toString());
         emppwtxt.setText(model.getValueAt(data, 4).toString());
         
    }//GEN-LAST:event_sTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M_UI_UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M_UI_UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M_UI_UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M_UI_UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M_UI_UserDetails("EXIT").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Emppwlb;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton detailsbtn;
    private javax.swing.JLabel empIDlb1;
    private javax.swing.JTextField empIDtxtq;
    private javax.swing.JLabel empagelb;
    private javax.swing.JTextField empagetxt;
    private javax.swing.JLabel empnamelb;
    private javax.swing.JTextField empnametxt;
    private javax.swing.JTextField emppwtxt;
    private javax.swing.JButton findbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lgoutbtn;
    private javax.swing.JButton newlsbtn1;
    private javax.swing.JButton refresh1;
    private javax.swing.JTable sTable2;
    private javax.swing.JButton switchbtn;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
