/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class S_UI_SALES extends javax.swing.JFrame {
   
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    public S_UI_SALES(String exit) {
        initComponents();
        bill();
        try {
            String url = "jdbc:mysql://localhost/Apple_iStore";
            String user = "root";
            String password = "";

            conn = DriverManager.getConnection(url, user, password);
            System.out.println("Connected!...");
        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
        
          String sql = "SELECT * FROM catagory";
          try {
            

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            if (rs.isBeforeFirst()) {
                while (rs.next()) {
                    combxt.addItem(rs.getString("Catagory"));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Product Records Not Found!");
            }

        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
          
         
    }
    public void bill(){
    String text ="";
         text +="    \t----------APPLE iSTORE--------- \n";
         text +="                     NO.123 , Ward Place/ Colombo 07\n";
         text +="                     Contact- 011234567/ 0712345678\n";
         text +="   ============================================\n";
         text +="   PRODUCT\t\t QUANTITY\tTOTAL\n";
         text +="   ____________________________________________\n";
         BILLTX.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tot = new javax.swing.JLabel();
        tottxt = new javax.swing.JTextField();
        qunlbl = new javax.swing.JLabel();
        quntxt = new javax.swing.JTextField();
        billbtn = new javax.swing.JButton();
        restbtn = new javax.swing.JButton();
        balance = new javax.swing.JLabel();
        cashtxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        BILLTX = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        billbt = new javax.swing.JButton();
        cash = new javax.swing.JLabel();
        balncetxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        qtxt = new javax.swing.JTextField();
        pnlable = new javax.swing.JLabel();
        combxt = new javax.swing.JComboBox<>();
        catlbl = new javax.swing.JLabel();
        Fillterbtn = new javax.swing.JButton();
        refreashbtn = new javax.swing.JButton();
        lgoutbtn = new javax.swing.JButton();
        deleteitmbtn = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        QLBL = new javax.swing.JLabel();
        prtxt = new javax.swing.JTextField();
        pnmtxt = new javax.swing.JTextField();
        plbl = new javax.swing.JLabel();
        PRIDLB = new javax.swing.JLabel();
        pridtxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        tot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tot.setForeground(new java.awt.Color(204, 204, 204));
        tot.setText("Total");

        tottxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tottxtActionPerformed(evt);
            }
        });

        qunlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qunlbl.setForeground(new java.awt.Color(204, 204, 204));
        qunlbl.setText("Quantity");

        quntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quntxtActionPerformed(evt);
            }
        });

        billbtn.setBackground(new java.awt.Color(153, 0, 0));
        billbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        billbtn.setForeground(new java.awt.Color(255, 255, 255));
        billbtn.setText("Add");
        billbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billbtnActionPerformed(evt);
            }
        });

        restbtn.setBackground(new java.awt.Color(153, 0, 0));
        restbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        restbtn.setForeground(new java.awt.Color(255, 255, 255));
        restbtn.setText("Reset");
        restbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restbtnActionPerformed(evt);
            }
        });

        balance.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        balance.setForeground(new java.awt.Color(204, 204, 204));
        balance.setText("Balance");

        cashtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashtxtActionPerformed(evt);
            }
        });

        BILLTX.setColumns(20);
        BILLTX.setRows(5);
        jScrollPane2.setViewportView(BILLTX);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product QTY", "Price"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        billbt.setBackground(new java.awt.Color(153, 0, 0));
        billbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        billbt.setForeground(new java.awt.Color(255, 255, 255));
        billbt.setText("Bill");
        billbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billbtActionPerformed(evt);
            }
        });

        cash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cash.setForeground(new java.awt.Color(204, 204, 204));
        cash.setText("Cash");

        balncetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balncetxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cash)
                                    .addComponent(balance)
                                    .addComponent(qunlbl)
                                    .addComponent(tot)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(billbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(billbt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(restbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(balncetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cashtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tottxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(quntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(qunlbl)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tot)
                            .addComponent(tottxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cashtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cash))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balncetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balance))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(restbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billbt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        producttable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Price"
            }
        ));
        producttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                producttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(producttable);

        qtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtxtActionPerformed(evt);
            }
        });

        pnlable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlable.setForeground(new java.awt.Color(204, 204, 204));
        pnlable.setText("Product Name");

        combxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        combxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combxtActionPerformed(evt);
            }
        });

        catlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        catlbl.setForeground(new java.awt.Color(204, 204, 204));
        catlbl.setText("Catagory");

        Fillterbtn.setBackground(new java.awt.Color(153, 0, 0));
        Fillterbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Fillterbtn.setForeground(new java.awt.Color(255, 255, 255));
        Fillterbtn.setText("Filter");
        Fillterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillterbtnActionPerformed(evt);
            }
        });

        refreashbtn.setBackground(new java.awt.Color(153, 0, 0));
        refreashbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        refreashbtn.setForeground(new java.awt.Color(255, 255, 255));
        refreashbtn.setText("Refresh");
        refreashbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreashbtnActionPerformed(evt);
            }
        });

        lgoutbtn.setBackground(new java.awt.Color(153, 0, 0));
        lgoutbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lgoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        lgoutbtn.setText("Logout");
        lgoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgoutbtnActionPerformed(evt);
            }
        });

        deleteitmbtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteitmbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deleteitmbtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteitmbtn.setText("Delete");
        deleteitmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteitmbtnActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(153, 0, 0));
        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        QLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        QLBL.setForeground(new java.awt.Color(204, 204, 204));
        QLBL.setText("Quantity");

        prtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prtxtActionPerformed(evt);
            }
        });

        pnmtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnmtxtActionPerformed(evt);
            }
        });

        plbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        plbl.setForeground(new java.awt.Color(204, 204, 204));
        plbl.setText("Price");

        PRIDLB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PRIDLB.setForeground(new java.awt.Color(204, 204, 204));
        PRIDLB.setText("Product ID");

        pridtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lgoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Fillterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(deleteitmbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pnlable)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(catlbl)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(plbl)
                                                    .addComponent(QLBL)))
                                            .addComponent(PRIDLB))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnmtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreashbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRIDLB)
                    .addComponent(pridtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlable)
                    .addComponent(pnmtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catlbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLBL))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fillterbtn)
                    .addComponent(deleteitmbtn)
                    .addComponent(update))
                .addGap(18, 18, 18)
                .addComponent(refreashbtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lgoutbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quntxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quntxtActionPerformed

    private void deleteitmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteitmbtnActionPerformed
        // TODO add your handling code here:
        try {
                M_UI_UserDetails frame = new M_UI_UserDetails ("Delete");
                if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to Delete Recode" ,
                        "Delete" ,JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
                {
            int id = Integer.parseInt(pridtxt.getText());

            String sql = "DELETE  FROM product_details WHERE Pro_ID=?";
            pst = conn.prepareStatement(sql);

            pst.setInt(1, id);

            if (pst.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Product Record Deleted");
            }
           }
        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
     
    }//GEN-LAST:event_deleteitmbtnActionPerformed

    private void lgoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgoutbtnActionPerformed
        // TODO add your handling code here:
        S_UI_SALES frame = new S_UI_SALES ("EXIT");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit" ,
                "EXIT" ,JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_lgoutbtnActionPerformed

    private void FillterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillterbtnActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(pridtxt.getText());
            
            String sql = "SELECT * FROM product_details WHERE Pro_ID=?";

            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            
            
            rs = pst.executeQuery();
            if (rs.isBeforeFirst()) {
                rs.first();
                pnmtxt.setText(rs.getString(1));
                //combxt.setSelectedItem(rs.getString(2));
                qtxt.setText(rs.getString(6));
                prtxt.setText(rs.getString(5));
                combxt.setSelectedItem(rs.getString(3));
                
              } else {
                JOptionPane.showMessageDialog(this, "Product Record Not Found!");
                clear();
            }

        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
    }//GEN-LAST:event_FillterbtnActionPerformed

    private void qtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtxtActionPerformed

    private void prtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prtxtActionPerformed

    private void pnmtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnmtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnmtxtActionPerformed

    private void refreashbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreashbtnActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM Product_details";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) producttable.getModel();
            model.setRowCount(0);
            if (rs.isBeforeFirst()) {
                while (rs.next()) {
                    model.addRow(new String[]{rs.getString(2),
                        rs.getString(1), rs.getString(6), rs.getString(5)});
                }
            } else {
                JOptionPane.showMessageDialog(this, "Product Records Not Found!");
            }

        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
    }//GEN-LAST:event_refreashbtnActionPerformed
int avaqt;
    private void producttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producttableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel)producttable.getModel();
        int data = producttable.getSelectedRow();
        pridtxt.setText(model.getValueAt(data, 0).toString());
        pnmtxt.setText(model.getValueAt(data, 1).toString());
        //combxt.setSelectedIndex(model.setValueAt(data, 2).toString());
        qtxt.setText(model.getValueAt(data, 2).toString());
        prtxt.setText(model.getValueAt(data, 3).toString());
        avaqt = Integer.valueOf(model.getValueAt(data, 2).toString());
            
    }//GEN-LAST:event_producttableMouseClicked

    private void cashtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashtxtActionPerformed

    private void combxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combxtActionPerformed
        // TODO add your handling code here:
         try {
            String sql = "SELECT * FROM Catagory";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
           } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
    }//GEN-LAST:event_combxtActionPerformed

    private void pridtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pridtxtActionPerformed
int i=0;
int sub =0;
    private void billbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billbtnActionPerformed
         try{
//             if (quntxt.getText().isEmpty())
//             {
//                 JOptionPane.showMessageDialog(this, "Missing Information");
             
             double price,ans;
             int quan;
             price= Double.parseDouble(prtxt.getText());
             quan= Integer.parseInt(quntxt.getText());

            ans= quan*price;
            sub +=ans;
            tottxt.setText(""+ans);
           //totallabel.setText(""+sub);
          }catch(Exception ex){
            System.out.println("error"+ ex.getMessage());
          }
           viewtable();
           clear();
    }
         public void viewtable(){
             
          DefaultTableModel model = new DefaultTableModel();
          model = (DefaultTableModel)jTable1.getModel();

          model.addRow(new Object[]{pnmtxt.getText(), quntxt.getText(), tottxt.getText()});

          BILLTX.setText(BILLTX.getText()+"\n\n"+ pnmtxt.getText()+"\t\t"+
                  quntxt.getText()+"\t"+ tottxt.getText());
         try{
         //sub = 0;
         for(int x=0; x<jTable1.getRowCount(); x++ ){
         sub= sub+Integer.parseInt(jTable1.getValueAt(x,2).toString());
         tottxt.setText(Integer.toString(sub));
   }
        }catch(Exception ex){
           JOptionPane.showMessageDialog(this, "Missing Information");
           System.out.println("error "+ ex.getMessage());
  }
    }//GEN-LAST:event_billbtnActionPerformed

    private void restbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restbtnActionPerformed
        // TODO add your handling code here:
        tottxt.setText("");
        cashtxt.setText("");
        quntxt.setText("");
        balncetxt.setText("");
        
    }//GEN-LAST:event_restbtnActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(pridtxt.getText());
            String name = pnmtxt.getText();
            int QN = Integer.parseInt(qtxt.getText());
            String pr = prtxt.getText();

            String sql = "UPDATE product_details SET Name=?, Price=?, Quantity=? WHERE Pro_ID=?";
            pst = conn.prepareStatement(sql);

            pst.setString(1, name);
            pst.setInt(3, QN);
            pst.setString(2, pr);
            pst.setInt(4, id);

            if (pst.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Product Record Updated");
                clear();
            }else{
                JOptionPane.showMessageDialog(this, "Product Record Not Updated");
                clear();
            }
        } catch (Exception ex) {
            System.out.println("Erorr : " + ex.getMessage());
        }
                
    }//GEN-LAST:event_updateActionPerformed

    private void billbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billbtActionPerformed
       try{
          double Cash,Balance;
          
           Cash= Double.parseDouble(cashtxt.getText());
           Balance= Cash - sub;
           balncetxt.setText(""+Balance);
           
          }catch(Exception ex){
            System.out.println("error"+ ex.getMessage());
          }       
         BILLTX.setText(BILLTX.getText()+"\n\nSub Total\t\t\t"+ sub +"\nCash\t\t\t"
                 +cashtxt.getText()+"\nBalance\t\t\t"+ balncetxt.getText());
          
    }//GEN-LAST:event_billbtActionPerformed

    private void balncetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balncetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balncetxtActionPerformed

    private void tottxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tottxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tottxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_UI_SALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_UI_SALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_UI_SALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_UI_SALES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_UI_SALES("EXIT").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BILLTX;
    private javax.swing.JButton Fillterbtn;
    private javax.swing.JLabel PRIDLB;
    private javax.swing.JLabel QLBL;
    private javax.swing.JLabel balance;
    private javax.swing.JTextField balncetxt;
    private javax.swing.JButton billbt;
    private javax.swing.JButton billbtn;
    private javax.swing.JLabel cash;
    private javax.swing.JTextField cashtxt;
    private javax.swing.JLabel catlbl;
    private javax.swing.JComboBox<String> combxt;
    private javax.swing.JButton deleteitmbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lgoutbtn;
    private javax.swing.JLabel plbl;
    private javax.swing.JLabel pnlable;
    private javax.swing.JTextField pnmtxt;
    private javax.swing.JTextField pridtxt;
    private javax.swing.JTable producttable;
    private javax.swing.JTextField prtxt;
    private javax.swing.JTextField qtxt;
    private javax.swing.JLabel qunlbl;
    private javax.swing.JTextField quntxt;
    private javax.swing.JButton refreashbtn;
    private javax.swing.JButton restbtn;
    private javax.swing.JLabel tot;
    private javax.swing.JTextField tottxt;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
